import { Schema } from "effect"

import * as ApprovalRequestErrors from "./errors-approval-requests.js"
import { HrDomainError } from "./errors-domain-hr.js"
import {
  BoardArchivedCardDeleteError,
  BoardCardIdentifierAmbiguousError,
  BoardCardNotFoundError,
  BoardIdentifierAmbiguousError,
  BoardLabelIdentifierAmbiguousError,
  BoardLabelNotFoundError,
  BoardMenuPageIdentifierAmbiguousError,
  BoardMenuPageNotFoundError,
  BoardModelSequenceMissingError,
  BoardMutationUnsupportedError,
  BoardNotFoundError,
  BoardProjectTypeIdentifierAmbiguousError,
  BoardProjectTypeNotFoundError,
  BoardSavedViewIdentifierAmbiguousError,
  BoardSavedViewNotFoundError,
  BoardStatusIdentifierAmbiguousError,
  BoardStatusNotFoundError,
  BoardTaskTypeIdentifierAmbiguousError,
  BoardTaskTypeNotFoundError,
  BoardViewletIdentifierAmbiguousError,
  BoardViewletNotFoundError
} from "./errors-boards.js"
import {
  CalendarNotAccessibleError,
  EventNotFoundError,
  RecurringEventNotFoundError,
  ScheduleNotFoundError
} from "./errors-calendar.js"
import {
  CardCommentNotFoundError,
  CardNotFoundError,
  CardSpaceNotFoundError,
  MasterTagNotFoundError
} from "./errors-cards.js"
import {
  ContactChannelConflictError,
  ContactChannelIdentifierAmbiguousError,
  ContactChannelNotFoundError,
  InvalidContactChannelLocatorError,
  InvalidContactChannelValueError,
  InvalidContactProviderError,
  InvalidPersonUuidError,
  OrganizationIdentifierAmbiguousError,
  OrganizationNotFoundError,
  PersonIdentifierAmbiguousError,
  PersonNotFoundError
} from "./errors-contacts.js"
import {
  CustomFieldNotFoundError,
  CustomFieldObjectNotFoundError,
  InvalidCustomFieldDateValueError
} from "./errors-custom-fields.js"
import {
  DocumentContentCorruptedError,
  DocumentEditModeError,
  DocumentEmptyContentError,
  DocumentNotFoundError,
  DocumentReferenceError,
  DocumentTextMultipleMatchesError,
  DocumentTextNotFoundError,
  TeamspaceNotFoundError
} from "./errors-documents.js"
import { HulyDomainBaseError } from "./errors-domain-base.js"
import { EmployeeLifecycleDomainError } from "./errors-domain-employee-lifecycle.js"
import { HulyMessagingDomainError } from "./errors-domain-messaging.js"
import { HulyViewDomainError } from "./errors-domain-view.js"
import { PersonAdministrationDomainError } from "./errors-person-administration.js"
import {
  DriveFileCommentNotFoundError,
  DriveFileNotFoundError,
  DriveFileVersionNotFoundError,
  DriveFolderNotEmptyError,
  DriveIdentifierAmbiguousError,
  DriveInvalidItemOperationError,
  DriveInvalidMoveError,
  DriveNotEmptyError,
  DriveNotFoundError,
  DriveParentNotFolderError,
  DrivePathAmbiguousError,
  DrivePathConflictError,
  DrivePathNotFoundError
} from "./errors-drive.js"
import {
  AttachmentContentTooLargeError,
  AttachmentContentTypeUnsupportedError,
  AttachmentContentUnavailableError,
  AttachmentNotFoundError,
  DrawingNotFoundError,
  FileFetchError,
  FileNotFoundError,
  FileTooLargeError,
  FileUploadError,
  HulyStorageConfigError,
  InvalidContentTypeError,
  InvalidFileDataError,
  SavedAttachmentNotFoundError
} from "./errors-files.js"
import {
  AssociationConflictError,
  AssociationIdentifierAmbiguousError,
  AssociationInUseError,
  AssociationNotFoundError,
  AssociationSystemClassUnsupportedError,
  GenericObjectIdentifierAmbiguousError,
  GenericObjectLocatorInvalidError,
  GenericObjectNotFoundError,
  RelationCardinalityViolationError,
  RelationDirectionAmbiguousError,
  RelationEndpointClassMismatchError,
  RelationIdentifierAmbiguousError,
  RelationMutationUnsupportedError,
  RelationNotFoundError
} from "./errors-generic-associations.js"
import {
  InventoryCategoryIdentifierAmbiguousError,
  InventoryCategoryNotFoundError,
  InventoryConflictError,
  InventoryMutationUnsupportedError,
  InventoryNotEmptyError,
  InventoryProductCommentNotFoundError,
  InventoryProductIdentifierAmbiguousError,
  InventoryProductNotFoundError,
  InventoryVariantIdentifierAmbiguousError,
  InventoryVariantNotFoundError
} from "./errors-inventory.js"
import { LabelDomainError } from "./errors-labels.js"
import { FunnelDomainError, LeadMutationDomainError, LeadNotFoundError } from "./errors-leads.js"
import { FloorNotFoundError, MeetingMinutesNotFoundError, RoomNotFoundError } from "./errors-love.js"
import { AdministrationDomainError } from "./errors-administration-domain.js"
import {
  NotificationContextNotFoundError,
  NotificationNotFoundError,
  NotificationPersonSpaceNotFoundError,
  NotificationProviderNotConfigurableError,
  NotificationProviderNotFoundError,
  NotificationTypeNotFoundError
} from "./errors-notifications.js"
import {
  PlannerSchedulingPrerequisiteError,
  TodoIdentifierAmbiguousError,
  TodoNotFoundError,
  TodoWorkSlotNotFoundError
} from "./errors-planner.js"
import {
  ProcessCardIdentifierAmbiguousError,
  ProcessCardNotFoundError,
  ProcessExecutionNotCancellableError,
  ProcessExecutionNotFoundError,
  ProcessIdentifierAmbiguousError,
  ProcessInitialStateNotFoundError,
  ProcessMasterTagAmbiguousError,
  ProcessMasterTagNotFoundError,
  ProcessNotFoundError,
  ProcessParallelExecutionForbiddenError
} from "./errors-processes.js"
import {
  RecruitingApplicantIdentifierAmbiguousError,
  RecruitingApplicantMatchNotFoundError,
  RecruitingApplicantNotFoundError,
  RecruitingAttachmentNotFoundError,
  RecruitingCandidateNotFoundError,
  RecruitingCommentNotFoundError,
  RecruitingDuplicateApplicantError,
  RecruitingIssueLocatorInvalidError,
  RecruitingModelMissingError,
  RecruitingMutationUnsupportedError,
  RecruitingOpinionIdentifierAmbiguousError,
  RecruitingOpinionNotFoundError,
  RecruitingReviewIdentifierAmbiguousError,
  RecruitingReviewNotFoundError,
  RecruitingVacancyIdentifierAmbiguousError,
  RecruitingVacancyNotFoundError,
  RecruitingVacancyTypeNotFoundError
} from "./errors-recruiting.js"
import { HulyClassNotFoundError } from "./errors-sdk-discovery.js"
import {
  SpaceIdentifierAmbiguousError,
  SpaceNotFoundError,
  SpaceNotTypedError,
  SpaceRoleAssignmentsMalformedError,
  SpaceRoleIdentifierAmbiguousError,
  SpaceRoleNotFoundError,
  SpaceCreationConflictError,
  SpaceTypeCreationUnsupportedError,
  SpaceTypeIdentifierAmbiguousError,
  SpaceTypeNotFoundError
} from "./errors-spaces.js"
import {
  MessageTemplateCategoryIdentifierAmbiguousError,
  MessageTemplateCategoryNotFoundError,
  MessageTemplateIdentifierAmbiguousError,
  MessageTemplateNotFoundError,
  TemplateFieldCategoryIdentifierAmbiguousError,
  TemplateFieldCategoryNotFoundError
} from "./errors-templates.js"
import {
  TestCaseNotFoundError,
  TestPlanItemNotFoundError,
  TestPlanNotFoundError,
  TestProjectNotFoundError,
  TestResultNotFoundError,
  TestRunNotFoundError,
  TestSuiteNotFoundError
} from "./errors-test-management.js"
import {
  CommentNotFoundError,
  ComponentNotFoundError,
  InvalidStatusError,
  IssueNotFoundError,
  IssueReferenceError,
  IssueTemplateNotFoundError,
  MilestoneIdentifierAmbiguousError,
  MilestoneNotFoundError,
  ProjectNotFoundError,
  TemplateChildNotFoundError
} from "./errors-tracker.js"
import { WorkflowStatusDomainError } from "./errors-workflow-statuses.js"

export const HulyDomainError = Schema.Union([
  HulyDomainBaseError,
  HulyViewDomainError,
  ApprovalRequestErrors.ApprovalRequestNotFoundError,
  ApprovalRequestErrors.ApprovalRequestTargetNotFoundError,
  ApprovalRequestErrors.ApprovalRequestInvalidApprovalThresholdError,
  ApprovalRequestErrors.ApprovalRequestMutationUnsupportedError,
  ApprovalRequestErrors.ApprovalRequestNotActiveError,
  ApprovalRequestErrors.ApprovalRequestApproverNotRequestedError,
  ApprovalRequestErrors.ApprovalRequestCancelUnauthorizedError,
  BoardNotFoundError,
  BoardIdentifierAmbiguousError,
  BoardCardNotFoundError,
  BoardCardIdentifierAmbiguousError,
  BoardProjectTypeNotFoundError,
  BoardProjectTypeIdentifierAmbiguousError,
  BoardTaskTypeNotFoundError,
  BoardTaskTypeIdentifierAmbiguousError,
  BoardStatusNotFoundError,
  BoardStatusIdentifierAmbiguousError,
  BoardArchivedCardDeleteError,
  BoardModelSequenceMissingError,
  BoardMutationUnsupportedError,
  BoardLabelNotFoundError,
  BoardLabelIdentifierAmbiguousError,
  BoardSavedViewNotFoundError,
  BoardSavedViewIdentifierAmbiguousError,
  BoardMenuPageNotFoundError,
  BoardMenuPageIdentifierAmbiguousError,
  BoardViewletNotFoundError,
  BoardViewletIdentifierAmbiguousError,
  IssueNotFoundError,
  IssueReferenceError,
  ProjectNotFoundError,
  InvalidStatusError,
  ContactChannelConflictError,
  ContactChannelIdentifierAmbiguousError,
  ContactChannelNotFoundError,
  InvalidContactChannelLocatorError,
  InvalidContactChannelValueError,
  PersonIdentifierAmbiguousError,
  PersonNotFoundError,
  EmployeeLifecycleDomainError,
  PersonAdministrationDomainError,
  OrganizationNotFoundError,
  OrganizationIdentifierAmbiguousError,
  InvalidContactProviderError,
  HrDomainError,
  FileUploadError,
  InvalidFileDataError,
  FileNotFoundError,
  FileFetchError,
  HulyStorageConfigError,
  TeamspaceNotFoundError,
  DocumentNotFoundError,
  DocumentTextNotFoundError,
  DocumentTextMultipleMatchesError,
  DocumentEmptyContentError,
  DocumentContentCorruptedError,
  DocumentEditModeError,
  DocumentReferenceError,
  CommentNotFoundError,
  MilestoneIdentifierAmbiguousError,
  MilestoneNotFoundError,
  HulyMessagingDomainError,
  CalendarNotAccessibleError,
  EventNotFoundError,
  RecurringEventNotFoundError,
  ScheduleNotFoundError,
  AttachmentNotFoundError,
  AttachmentContentTooLargeError,
  AttachmentContentTypeUnsupportedError,
  AttachmentContentUnavailableError,
  SavedAttachmentNotFoundError,
  DrawingNotFoundError,
  CardSpaceNotFoundError,
  CardNotFoundError,
  CardCommentNotFoundError,
  MasterTagNotFoundError,
  LabelDomainError,
  InventoryCategoryNotFoundError,
  InventoryProductNotFoundError,
  InventoryVariantNotFoundError,
  InventoryCategoryIdentifierAmbiguousError,
  InventoryProductIdentifierAmbiguousError,
  InventoryVariantIdentifierAmbiguousError,
  InventoryConflictError,
  InventoryNotEmptyError,
  InventoryMutationUnsupportedError,
  InventoryProductCommentNotFoundError,
  TestProjectNotFoundError,
  TestSuiteNotFoundError,
  TestCaseNotFoundError,
  TestPlanNotFoundError,
  TestRunNotFoundError,
  TestResultNotFoundError,
  TestPlanItemNotFoundError,
  ComponentNotFoundError,
  CustomFieldNotFoundError,
  CustomFieldObjectNotFoundError,
  InvalidCustomFieldDateValueError,
  IssueTemplateNotFoundError,
  TemplateChildNotFoundError,
  NotificationNotFoundError,
  NotificationContextNotFoundError,
  NotificationPersonSpaceNotFoundError,
  NotificationProviderNotFoundError,
  NotificationTypeNotFoundError,
  NotificationProviderNotConfigurableError,
  InvalidPersonUuidError,
  FunnelDomainError,
  LeadNotFoundError,
  LeadMutationDomainError,
  FloorNotFoundError,
  RoomNotFoundError,
  MeetingMinutesNotFoundError,
  FileTooLargeError,
  InvalidContentTypeError,
  ProcessNotFoundError,
  ProcessIdentifierAmbiguousError,
  ProcessMasterTagAmbiguousError,
  ProcessMasterTagNotFoundError,
  ProcessCardIdentifierAmbiguousError,
  ProcessCardNotFoundError,
  ProcessInitialStateNotFoundError,
  ProcessParallelExecutionForbiddenError,
  ProcessExecutionNotFoundError,
  ProcessExecutionNotCancellableError,
  RecruitingApplicantIdentifierAmbiguousError,
  RecruitingApplicantMatchNotFoundError,
  RecruitingApplicantNotFoundError,
  RecruitingAttachmentNotFoundError,
  RecruitingCandidateNotFoundError,
  RecruitingCommentNotFoundError,
  RecruitingDuplicateApplicantError,
  RecruitingIssueLocatorInvalidError,
  RecruitingModelMissingError,
  RecruitingMutationUnsupportedError,
  RecruitingOpinionIdentifierAmbiguousError,
  RecruitingOpinionNotFoundError,
  RecruitingReviewIdentifierAmbiguousError,
  RecruitingReviewNotFoundError,
  RecruitingVacancyIdentifierAmbiguousError,
  RecruitingVacancyNotFoundError,
  RecruitingVacancyTypeNotFoundError,
  AssociationNotFoundError,
  AssociationIdentifierAmbiguousError,
  AssociationSystemClassUnsupportedError,
  AssociationConflictError,
  AssociationInUseError,
  RelationNotFoundError,
  RelationIdentifierAmbiguousError,
  RelationMutationUnsupportedError,
  RelationCardinalityViolationError,
  RelationDirectionAmbiguousError,
  RelationEndpointClassMismatchError,
  GenericObjectIdentifierAmbiguousError,
  GenericObjectLocatorInvalidError,
  GenericObjectNotFoundError,
  HulyClassNotFoundError,
  AdministrationDomainError,
  SpaceNotFoundError,
  SpaceIdentifierAmbiguousError,
  SpaceNotTypedError,
  SpaceRoleNotFoundError,
  SpaceRoleIdentifierAmbiguousError,
  SpaceRoleAssignmentsMalformedError,
  SpaceCreationConflictError,
  SpaceTypeCreationUnsupportedError,
  SpaceTypeNotFoundError,
  SpaceTypeIdentifierAmbiguousError,
  TodoNotFoundError,
  TodoIdentifierAmbiguousError,
  TodoWorkSlotNotFoundError,
  PlannerSchedulingPrerequisiteError,
  DriveNotFoundError,
  DriveIdentifierAmbiguousError,
  DrivePathNotFoundError,
  DrivePathAmbiguousError,
  DriveParentNotFolderError,
  DriveFileCommentNotFoundError,
  DriveFileNotFoundError,
  DriveFileVersionNotFoundError,
  DrivePathConflictError,
  DriveInvalidMoveError,
  DriveInvalidItemOperationError,
  DriveFolderNotEmptyError,
  DriveNotEmptyError,
  MessageTemplateCategoryNotFoundError,
  MessageTemplateCategoryIdentifierAmbiguousError,
  MessageTemplateNotFoundError,
  MessageTemplateIdentifierAmbiguousError,
  TemplateFieldCategoryNotFoundError,
  TemplateFieldCategoryIdentifierAmbiguousError,
  WorkflowStatusDomainError
])

export type HulyDomainError = Schema.Schema.Type<typeof HulyDomainError>
